### ISSUE TITLE
Support for more recent AS versions?

### ISSUE THREAD

**Issue by dmolesUC** [hudmol/digitization_work_order#22]
Is this plugin known **not** to work with versions > 2.1.x, or has it just not been tested? (We're running 2.8.)

**Comment by jambun** [comment]
That might just be lagging documentation ;)

I'm pretty sure it's running on 2.7-ish. I would check in with the folks at Yale.

**Comment by dmolesUC** [comment]
Thanks!

**Comment by triplingual** [comment]
To close the loop from our end, yes, we are running it successfully in production on our modestly modded 2.7.1.

**Comment by triebwad** [comment]
We are testing on v2.8.1 and it looks like its working correctly. We are using default configuration
